version: "3.8"

volumes:
  postgres_data:  # Renamed for clarity
    name: postgres_data

services:
  db:
    image: postgres:latest
    user: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres-db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: task_manager_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres-db
      - DB_HOST=db  # Docker service name for the database
      - DB_PORT=5432  # Use the internal port of the db container (not host-mapped)
